/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_litongjava_androidndkdem02_MyNdk */

#ifndef _Included_com_litongjava_androidndkdem02_MyNdk
#define _Included_com_litongjava_androidndkdem02_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_litongjava_androidndkdem02_MyNdk
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_litongjava_androidndkdem02_MyNdk_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_litongjava_androidndkdem02_MyNdk
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_litongjava_androidndkdem02_MyNdk_getMyString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
